### ISSUE TITLE
Can you please add the file with all of the requirements.

### ISSUE THREAD

**Issue by Potato-git13** [No-Cellist-7780/goddit#3]
It was my first time installing go for this and when I run it I get [this](https://pastebin.com/mW16AGFy).
Can you add a file with requirements and how to install them?

**Comment by No-Cellist-7780** [comment]
Unlike python there is no need for a requirements.txt just run go get . in the goddit folder inside the repo , it will install all the dependencies on its own or u can use the binary from the releases if u are running Linux

**Comment by Potato-git13** [comment]
Thank you for the answer but when I try it I get this.:
```
go get: no install location for directory /home/potato/goddit/goddit outside GOPATH
        For more details see: 'go help gopath'
```
I searched a bit on the internet and I have come to the conclusion that the repo is not a valid GO workspace. That may as well be very wrong but I don't know how to set the GOPATH. Was I supposed  to clone the repo to my $HOME/go directory?

I appreciate your help.

**Comment by No-Cellist-7780** [comment]
There was no need for that in particular , you can use golang in ur home directory as well by exporting the env variable, i.e. `export GOPATH=$HOME` or if you were using a debian based system u can simply download go using `sudo apt install golang` the benifit of that is it sets $GOHOME and $GOPATH variables automatically
